### ISSUE TITLE
pacman signature for arkos repository

### ISSUE THREAD

**Issue by alon7786** [cznweb/arkos-scripts#2]
The install script failed with untrusted signature.
the repository signature added but not grunted permissions:
`gpg --homedir /etc/pacman.d/gnupg --list-keys`
`[  unknown  ] Jacob Cook (arkOS Package Signing) <jacob@citizenweb.io>`
to fix to **full**
`pacman-key -lsign 0585F850`

**Comment by peakwinter** [comment]
Thanks for pointing this out! It should be fixed with f096219.
